name: Feature Request
description: Suggest an idea for Miniblox Translation Layer
labels: [enhancement]
body:
- type: checkboxes
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed all of the following.
    options:
      - label: I am not a pest
        required: true
      - label: I am using the latest version of Miniblox Translation Layer (`git pull`)
        required: true
      - label: My Minecraft client is running on 1.8.9 (you can use ViaVersion)
        required: true
      - label: I have searched the issues of this repository and believe that this is not a duplicate
        required: true
- type: textarea
  attributes:
    label: Problem Description
    description: Please add a clear and concise description of the problem you are seeking to solve with this feature request.
  validations:
    required: true
- type: textarea
  attributes:
    label: Proposed Solution
    description: Describe the solution you'd like in a clear and concise manner.
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternatives Considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: Add any other context about the problem here.
  validations:
    required: false