const mcData = require('minecraft-data')("1.8.9");
/**
 * The keys are the Miniblox item IDs, and the values are the Minecraft item IDs.
 * @type Object<number, number | [number, number]>
 */
let itemIDs = {};

for (let i = 0; i < 14; i++) itemIDs[1 + i] = [mcData.itemsByName.stone.id, i];
itemIDs[14] = mcData.itemsByName.grass.id;
for (let i = 0; i < 2; i++) itemIDs[15 + i] = mcData.itemsByName.dirt.id;
itemIDs[21] = mcData.itemsByName.cobblestone.id;
for (let i = 0; i < 8; i++) itemIDs[22 + i] = [mcData.itemsByName.planks.id, i % 6];
for (let i = 0; i < 6; i++) itemIDs[30 + i] = [mcData.itemsByName.sapling, i];
itemIDs[36] = mcData.itemsByName.bedrock.id;
for (let i = 0; i < 2; i++) itemIDs[37 + i] = [mcData.itemsByName.sand.id, i];
itemIDs[39] = mcData.itemsByName.gravel.id;
for (let i = 0; i < 2; i++) itemIDs[40 + i] = mcData.itemsByName.coal_ore.id;
for (let i = 0; i < 2; i++) itemIDs[42 + i] = mcData.itemsByName.iron_ore.id;
for (let i = 0; i < 2; i++) itemIDs[46 + i] = mcData.itemsByName.gold_ore.id;
for (let i = 0; i < 2; i++) itemIDs[48 + i] = mcData.itemsByName.redstone_ore.id;
for (let i = 0; i < 2; i++) itemIDs[50 + i] = mcData.itemsByName.emerald_ore.id;
for (let i = 0; i < 2; i++) itemIDs[52 + i] = mcData.itemsByName.lapis_ore.id;
for (let i = 0; i < 2; i++) itemIDs[54 + i] = mcData.itemsByName.diamond_ore.id;
itemIDs[65] = mcData.itemsByName.iron_block.id;
itemIDs[67] = mcData.itemsByName.gold_block.id;
for (let i = 0; i < 2; i++) itemIDs[68 + i] = mcData.itemsByName.diamond_block.id;
for (let i = 0; i < 4; i++) {
    itemIDs[101 + i] = [mcData.itemsByName.log.id, i];
    itemIDs[109 + i] = [mcData.itemsByName.log.id, i];
    itemIDs[125 + i] = [mcData.itemsByName.log.id, i];
}
for (let i = 0; i < 2; i++) {
    itemIDs[105 + i] = [mcData.itemsByName.log2.id, i];
    itemIDs[113 + i] = [mcData.itemsByName.log2.id, i];
    itemIDs[129 + i] = [mcData.itemsByName.log2.id, i];
}
for (let i = 0; i < 2; i++) itemIDs[141 + i] = [mcData.itemsByName.sponge.id, i];
itemIDs[143] = mcData.itemsByName.glass.id;
itemIDs[144] = mcData.itemsByName.stained_glass.id;
itemIDs[145] = mcData.itemsByName.lapis_block.id;
for (let i = 0; i < 3; i++) itemIDs[146 + i] = [mcData.itemsByName.sandstone.id, i];
itemIDs[149] = mcData.itemsByName.web.id;
itemIDs[150] = mcData.itemsByName.grass.id;
itemIDs[151] = [mcData.itemsByName.tallgrass.id, 2];
itemIDs[154] = mcData.itemsByName.deadbush.id;
for (let i = 0; i < 16; i++) itemIDs[157 + i] = [mcData.itemsByName.wool.id, i];
itemIDs[196] = mcData.itemsByName.reeds.id;
for (let i = 0; i < 8; i++) itemIDs[204 + i] = [mcData.itemsByName.wooden_slab.id, i % 6];
for (let i = 0; i < 3; i++) itemIDs[212 + i] = [mcData.itemsByName.stone_slab.id, i];
itemIDs[232] = mcData.itemsByName.brick_block.id;
itemIDs[233] = mcData.itemsByName.bookshelf.id;
itemIDs[234] = mcData.itemsByName.mossy_cobblestone.id;
itemIDs[235] = mcData.itemsByName.obsidian.id;
itemIDs[236] = mcData.itemsByName.torch.id;
itemIDs[243] = mcData.itemsByName.mob_spawner.id;
itemIDs[244] = mcData.itemsByName.oak_stairs.id;
itemIDs[245] = mcData.itemsByName.chest.id;
itemIDs[246] = mcData.itemsByName.crafting_table.id;
itemIDs[248] = mcData.itemsByName.furnace.id;
itemIDs[249] = mcData.itemsByName.ladder.id;
itemIDs[250] = mcData.itemsByName.cobblestone.id;
itemIDs[251] = mcData.itemsByName.snow.id;
itemIDs[252] = mcData.itemsByName.ice.id;
itemIDs[253] = mcData.itemsByName.snow.id;
itemIDs[254] = mcData.itemsByName.cactus.id;
itemIDs[256] = mcData.itemsByName.jukebox.id;
itemIDs[265] = mcData.itemsByName.pumpkin.id;
itemIDs[292] = mcData.itemsByName.brown_mushroom_block.id;
itemIDs[293] = mcData.itemsByName.red_mushroom_block.id;
itemIDs[297] = mcData.itemsByName.glass_pane.id;
itemIDs[298] = mcData.itemsByName.melon.id;
itemIDs[312] = mcData.itemsByName.end_stone.id;
itemIDs[314] = mcData.itemsByName.dragon_egg.id;
itemIDs[315] = mcData.itemsByName.sandstone_stairs.id;
itemIDs[316] = mcData.itemsByName.ender_chest.id;
itemIDs[317] = mcData.itemsByName.emerald_block.id;
itemIDs[318] = mcData.itemsByName.spruce_stairs.id;
itemIDs[319] = mcData.itemsByName.birch_stairs.id;
itemIDs[320] = mcData.itemsByName.jungle_stairs.id;
itemIDs[321] = mcData.itemsByName.birch_stairs.id;
itemIDs[322] = mcData.itemsByName.birch_stairs.id;
itemIDs[323] = mcData.itemsByName.command_block.id;
itemIDs[324] = mcData.itemsByName.beacon.id;
for (let i = 0; i < 3; i++) itemIDs[346 + i] = [mcData.itemsByName.anvil.id, i];
for (let i = 0; i < 16; i++) itemIDs[354 + i] = [mcData.itemsByName.stained_hardened_clay.id, i];
itemIDs[370] = mcData.itemsByName.barrier.id;
itemIDs[372] = mcData.itemsByName.hay_block.id;
for (let i = 0; i < 16; i++) itemIDs[373 + i] = [mcData.itemsByName.carpet.id, i];
itemIDs[389] = mcData.itemsByName.stained_hardened_clay.id;
itemIDs[390] = mcData.itemsByName.packed_ice.id;
for (let i = 0; i < 16; i++) itemIDs[400 + i] = [mcData.itemsByName.stained_glass.id, i];
for (let i = 0; i < 32; i++) itemIDs[468 + i] = [mcData.itemsByName.stained_hardened_clay.id, i % 16];
itemIDs[547] = mcData.itemsByName.ice.id;
itemIDs[585] = mcData.itemsByName.redstone.id;
itemIDs[586] = mcData.itemsByName.redstone_torch.id;
itemIDs[587] = mcData.itemsByName.redstone_block.id;
itemIDs[588] = mcData.itemsByName.repeater.id;
itemIDs[589] = mcData.itemsByName.comparator.id;
itemIDs[590] = mcData.itemsByName.piston.id;
itemIDs[591] = mcData.itemsByName.sticky_piston.id;
itemIDs[592] = mcData.itemsByName.slime.id;
itemIDs[595] = mcData.itemsByName.hopper.id;
itemIDs[596] = mcData.itemsByName.dispenser.id;
itemIDs[597] = mcData.itemsByName.dropper.id;
itemIDs[600] = mcData.itemsByName.lever.id;
itemIDs[604] = mcData.itemsByName.tripwire_hook.id;
itemIDs[605] = mcData.itemsByName.trapped_chest.id;
itemIDs[606] = mcData.itemsByName.tnt.id;
itemIDs[608] = mcData.itemsByName.noteblock.id;
itemIDs[609] = mcData.itemsByName.stone_button.id;
for (let i = 0; i < 8; i++) itemIDs[611 + i] = mcData.itemsByName.wooden_button.id;
for (let i = 0; i < 8; i++) itemIDs[623 + i] = mcData.itemsByName.wooden_pressure_plate.id;
itemIDs[631] = mcData.itemsByName.iron_door.id;
itemIDs[632] = mcData.itemsByName.wooden_door.id;
itemIDs[633] = mcData.itemsByName.spruce_door.id;
itemIDs[634] = mcData.itemsByName.birch_door.id;
itemIDs[635] = mcData.itemsByName.jungle_door.id;
itemIDs[636] = mcData.itemsByName.acacia_door.id;
itemIDs[637] = mcData.itemsByName.dark_oak_door.id;
itemIDs[638] = mcData.itemsByName.wooden_door.id;
itemIDs[639] = mcData.itemsByName.wooden_door.id;
itemIDs[640] = mcData.itemsByName.iron_trapdoor.id;
for (let i = 0; i < 8; i++) itemIDs[641 + i] = mcData.itemsByName.trapdoor.id;
itemIDs[680] = mcData.itemsByName.flint_and_steel.id;
itemIDs[681] = mcData.itemsByName.apple.id;
itemIDs[682] = mcData.itemsByName.bow.id;
itemIDs[683] = mcData.itemsByName.arrow.id;
itemIDs[684] = mcData.itemsByName.coal.id;
itemIDs[685] = [mcData.itemsByName.coal.id, 1];
itemIDs[686] = mcData.itemsByName.diamond.id;
itemIDs[687] = mcData.itemsByName.emerald.id;
itemIDs[688] = [mcData.itemsByName.dye.id, 4];
itemIDs[692] = mcData.itemsByName.iron_ingot.id;
itemIDs[696] = mcData.itemsByName.gold_ingot.id;
itemIDs[699] = mcData.itemsByName.wooden_sword.id;
itemIDs[700] = mcData.itemsByName.wooden_shovel.id;
itemIDs[701] = mcData.itemsByName.wooden_pickaxe.id;
itemIDs[702] = mcData.itemsByName.wooden_axe.id;
itemIDs[703] = mcData.itemsByName.wooden_hoe.id;
itemIDs[704] = mcData.itemsByName.stone_sword.id;
itemIDs[705] = mcData.itemsByName.stone_shovel.id;
itemIDs[706] = mcData.itemsByName.stone_pickaxe.id;
itemIDs[707] = mcData.itemsByName.stone_axe.id;
itemIDs[708] = mcData.itemsByName.stone_hoe.id;
itemIDs[709] = mcData.itemsByName.golden_sword.id;
itemIDs[710] = mcData.itemsByName.golden_shovel.id;
itemIDs[711] = mcData.itemsByName.golden_pickaxe.id;
itemIDs[712] = mcData.itemsByName.golden_axe.id;
itemIDs[713] = mcData.itemsByName.golden_hoe.id;
itemIDs[714] = mcData.itemsByName.iron_sword.id;
itemIDs[715] = mcData.itemsByName.iron_shovel.id;
itemIDs[716] = mcData.itemsByName.iron_pickaxe.id;
itemIDs[717] = mcData.itemsByName.iron_axe.id;
itemIDs[718] = mcData.itemsByName.iron_hoe.id;
itemIDs[719] = mcData.itemsByName.diamond_sword.id;
itemIDs[720] = mcData.itemsByName.diamond_shovel.id;
itemIDs[721] = mcData.itemsByName.diamond_pickaxe.id;
itemIDs[722] = mcData.itemsByName.diamond_axe.id;
itemIDs[723] = mcData.itemsByName.diamond_hoe.id;
itemIDs[724] = mcData.itemsByName.diamond_sword.id;
itemIDs[725] = mcData.itemsByName.diamond_shovel.id;
itemIDs[726] = mcData.itemsByName.diamond_pickaxe.id;
itemIDs[727] = mcData.itemsByName.diamond_axe.id;
itemIDs[728] = mcData.itemsByName.diamond_hoe.id;
itemIDs[729] = mcData.itemsByName.stick.id;
itemIDs[730] = mcData.itemsByName.bowl.id;
itemIDs[731] = mcData.itemsByName.mushroom_stew.id;
itemIDs[732] = mcData.itemsByName.string.id;
itemIDs[733] = mcData.itemsByName.feather.id;
itemIDs[734] = mcData.itemsByName.gunpowder.id;
itemIDs[735] = mcData.itemsByName.wheat_seeds.id;
itemIDs[736] = mcData.itemsByName.wheat.id;
itemIDs[737] = mcData.itemsByName.bread.id;
itemIDs[738] = mcData.itemsByName.leather_helmet.id;
itemIDs[739] = mcData.itemsByName.leather_chestplate.id;
itemIDs[740] = mcData.itemsByName.leather_leggings.id;
itemIDs[741] = mcData.itemsByName.leather_boots.id;
itemIDs[742] = mcData.itemsByName.chainmail_helmet.id;
itemIDs[743] = mcData.itemsByName.chainmail_chestplate.id;
itemIDs[744] = mcData.itemsByName.chainmail_leggings.id;
itemIDs[745] = mcData.itemsByName.chainmail_boots.id;
itemIDs[746] = mcData.itemsByName.iron_helmet.id;
itemIDs[747] = mcData.itemsByName.iron_chestplate.id;
itemIDs[748] = mcData.itemsByName.iron_leggings.id;
itemIDs[749] = mcData.itemsByName.iron_boots.id;
itemIDs[750] = mcData.itemsByName.diamond_helmet.id;
itemIDs[751] = mcData.itemsByName.diamond_chestplate.id;
itemIDs[752] = mcData.itemsByName.diamond_leggings.id;
itemIDs[753] = mcData.itemsByName.diamond_boots.id;
itemIDs[754] = mcData.itemsByName.golden_helmet.id;
itemIDs[755] = mcData.itemsByName.golden_chestplate.id;
itemIDs[756] = mcData.itemsByName.golden_leggings.id;
itemIDs[757] = mcData.itemsByName.golden_boots.id;
itemIDs[758] = mcData.itemsByName.diamond_helmet.id;
itemIDs[759] = mcData.itemsByName.diamond_chestplate.id;
itemIDs[760] = mcData.itemsByName.diamond_leggings.id;
itemIDs[761] = mcData.itemsByName.diamond_boots.id;
itemIDs[762] = mcData.itemsByName.flint.id;
itemIDs[763] = mcData.itemsByName.porkchop.id;
itemIDs[764] = mcData.itemsByName.cooked_porkchop.id;
itemIDs[766] = mcData.itemsByName.golden_apple.id;
itemIDs[767] = [mcData.itemsByName.golden_apple.id, 1];
for (let i = 0; i < 8; i++) itemIDs[768 + i] = mcData.itemsByName.sign.id;
itemIDs[776] = mcData.itemsByName.bucket.id;
itemIDs[777] = mcData.itemsByName.water_bucket.id;
itemIDs[778] = mcData.itemsByName.lava_bucket.id;
itemIDs[779] = mcData.itemsByName.water_bucket.id;
itemIDs[780] = mcData.itemsByName.snowball.id;
itemIDs[781] = mcData.itemsByName.leather.id;
itemIDs[782] = mcData.itemsByName.milk_bucket.id;
itemIDs[791] = mcData.itemsByName.paper.id;
itemIDs[792] = mcData.itemsByName.book.id;
itemIDs[793] = mcData.itemsByName.slime_ball.id;
itemIDs[794] = mcData.itemsByName.egg.id;
itemIDs[795] = mcData.itemsByName.compass.id;
itemIDs[797] = mcData.itemsByName.fishing_rod.id;
itemIDs[798] = mcData.itemsByName.clock.id;
for (let i = 0; i < 4; i++) itemIDs[801 + i] = [mcData.itemsByName.fish.id, i];
for (let i = 0; i < 2; i++) itemIDs[805 + i] = [mcData.itemsByName.cooked_fish.id, i];
for (let i = 0; i < 2; i++) itemIDs[807 + i] = mcData.itemsByName.dye.id;
itemIDs[809] = [mcData.itemsByName.dye.id, 3];
for (let i = 0; i < 16; i++) itemIDs[810 + i] = [mcData.itemsByName.dye.id, 15 - i];
itemIDs[826] = [mcData.itemsByName.dye.id, 15];
itemIDs[827] = mcData.itemsByName.bone.id;
itemIDs[828] = mcData.itemsByName.sugar.id;
itemIDs[829] = mcData.itemsByName.cake.id;
for (let i = 0; i < 16; i++) itemIDs[830 + i] = mcData.itemsByName.bed.id;
itemIDs[846] = mcData.itemsByName.cookie.id;
itemIDs[847] = 358; // FILLED_MAP
itemIDs[848] = mcData.itemsByName.shears.id;
itemIDs[849] = mcData.itemsByName.melon.id;
itemIDs[851] = mcData.itemsByName.pumpkin_seeds.id;
itemIDs[852] = mcData.itemsByName.melon_seeds.id;
itemIDs[853] = mcData.itemsByName.beef.id;
itemIDs[854] = mcData.itemsByName.cooked_beef.id;
itemIDs[855] = mcData.itemsByName.chicken.id;
itemIDs[856] = mcData.itemsByName.cooked_chicken.id;
itemIDs[857] = mcData.itemsByName.rotten_flesh.id;
itemIDs[858] = mcData.itemsByName.ender_pearl.id;
itemIDs[859] = mcData.itemsByName.blaze_rod.id;
itemIDs[860] = mcData.itemsByName.ghast_tear.id;
itemIDs[861] = mcData.itemsByName.gold_nugget.id;
itemIDs[863] = mcData.itemsByName.potion.id;
itemIDs[864] = mcData.itemsByName.glass_bottle.id;
itemIDs[865] = mcData.itemsByName.spider_eye.id;
itemIDs[866] = mcData.itemsByName.fermented_spider_eye.id;
itemIDs[867] = mcData.itemsByName.blaze_powder.id;
itemIDs[868] = mcData.itemsByName.magma_cream.id;
itemIDs[869] = mcData.itemsByName.brewing_stand.id;
itemIDs[870] = mcData.itemsByName.cauldron.id;
itemIDs[871] = mcData.itemsByName.ender_eye.id;
itemIDs[872] = mcData.itemsByName.speckled_melon.id;
itemIDs[940] = mcData.itemsByName.experience_bottle.id;
itemIDs[941] = mcData.itemsByName.fire_charge.id;
itemIDs[942] = mcData.itemsByName.writable_book.id;
itemIDs[943] = mcData.itemsByName.written_book.id;
for (let i = 0; i < 2; i++) itemIDs[944 + i] = mcData.itemsByName.item_frame.id;
itemIDs[946] = mcData.itemsByName.flower_pot.id;
itemIDs[947] = mcData.itemsByName.carrot.id;
itemIDs[948] = mcData.itemsByName.potato.id;
itemIDs[949] = mcData.itemsByName.baked_potato.id;
itemIDs[950] = mcData.itemsByName.poisonous_potato.id;
itemIDs[951] = mcData.itemsByName.map.id;
itemIDs[952] = mcData.itemsByName.golden_carrot.id;
itemIDs[960] = mcData.itemsByName.pumpkin_pie.id;
itemIDs[967] = mcData.itemsByName.rabbit.id;
itemIDs[968] = mcData.itemsByName.cooked_rabbit.id;
itemIDs[969] = mcData.itemsByName.rabbit_stew.id;
itemIDs[973] = mcData.itemsByName.iron_horse_armor.id;
itemIDs[974] = mcData.itemsByName.golden_horse_armor.id;
itemIDs[975] = mcData.itemsByName.diamond_horse_armor.id;
itemIDs[976] = mcData.itemsByName.iron_horse_armor.id;
itemIDs[977] = mcData.itemsByName.lead.id;
itemIDs[978] = mcData.itemsByName.name_tag.id;
itemIDs[980] = mcData.itemsByName.mutton.id;
itemIDs[981] = mcData.itemsByName.cooked_mutton.id;
itemIDs[998] = [mcData.itemsByName.spawn_egg.id, 200];
itemIDs[1005] = [mcData.itemsByName.potion.id, 1];
itemIDs[1015] = mcData.itemsByName.record_13.id;
itemIDs[1016] = mcData.itemsByName.record_cat.id;
itemIDs[1017] = mcData.itemsByName.record_blocks.id;
itemIDs[1018] = mcData.itemsByName.record_chirp.id;
itemIDs[1019] = mcData.itemsByName.record_far.id;
itemIDs[1020] = mcData.itemsByName.record_mall.id;
itemIDs[1021] = mcData.itemsByName.record_mellohi.id;
itemIDs[1022] = mcData.itemsByName.record_stal.id;
itemIDs[1023] = mcData.itemsByName.record_strad.id;
itemIDs[1024] = mcData.itemsByName.record_ward.id;
itemIDs[1025] = mcData.itemsByName.record_11.id;
itemIDs[1026] = mcData.itemsByName.record_wait.id;
itemIDs[1027] = mcData.itemsByName.record_stal.id;
itemIDs[1028] = mcData.itemsByName.record_stal.id;
itemIDs[1033] = mcData.itemsByName.bow.id;
itemIDs[1101] = mcData.itemsByName.diamond_sword.id;
itemIDs[1102] = mcData.itemsByName.diamond_pickaxe.id;
itemIDs[1103] = mcData.itemsByName.diamond_axe.id;
itemIDs[1104] = mcData.itemsByName.diamond_shovel.id;
itemIDs[1105] = mcData.itemsByName.diamond_hoe.id;
itemIDs[1106] = mcData.itemsByName.diamond_helmet.id;
itemIDs[1107] = mcData.itemsByName.diamond_chestplate.id;
itemIDs[1108] = mcData.itemsByName.diamond_leggings.id;
itemIDs[1109] = mcData.itemsByName.diamond_boots.id;
itemIDs[1110] = mcData.itemsByName.ladder.id;
itemIDs[1111] = mcData.itemsByName.apple.id;
module.exports = itemIDs;