const mcData = (await import('minecraft-data')).default("1.8.9");

let exports = [];
for (let i = 0; i < 14; i++) exports[1 + i] = [mcData.itemsByName.stone.id, i];
exports[14] = mcData.itemsByName.grass.id;
for (let i = 0; i < 2; i++) exports[15 + i] = mcData.itemsByName.dirt.id;
exports[21] = mcData.itemsByName.cobblestone.id;
for (let i = 0; i < 8; i++) exports[22 + i] = [mcData.itemsByName.planks.id, i % 6];
for (let i = 0; i < 6; i++) exports[30 + i] = [mcData.itemsByName.sapling, i];
exports[36] = mcData.itemsByName.bedrock.id;
for (let i = 0; i < 2; i++) exports[37 + i] = [mcData.itemsByName.sand.id, i];
exports[39] = mcData.itemsByName.gravel.id;
for (let i = 0; i < 2; i++) exports[40 + i] = mcData.itemsByName.coal_ore.id;
for (let i = 0; i < 2; i++) exports[42 + i] = mcData.itemsByName.iron_ore.id;
for (let i = 0; i < 2; i++) exports[46 + i] = mcData.itemsByName.gold_ore.id;
for (let i = 0; i < 2; i++) exports[48 + i] = mcData.itemsByName.redstone_ore.id;
for (let i = 0; i < 2; i++) exports[50 + i] = mcData.itemsByName.emerald_ore.id;
for (let i = 0; i < 2; i++) exports[52 + i] = mcData.itemsByName.lapis_ore.id;
for (let i = 0; i < 2; i++) exports[54 + i] = mcData.itemsByName.diamond_ore.id;
exports[65] = mcData.itemsByName.iron_block.id;
exports[67] = mcData.itemsByName.gold_block.id;
for (let i = 0; i < 2; i++) exports[68 + i] = mcData.itemsByName.diamond_block.id;
for (let i = 0; i < 4; i++) {
    exports[101 + i] = [mcData.itemsByName.log.id, i];
    exports[109 + i] = [mcData.itemsByName.log.id, i];
    exports[125 + i] = [mcData.itemsByName.log.id, i];
}
for (let i = 0; i < 2; i++) {
    exports[105 + i] = [mcData.itemsByName.log2.id, i];
    exports[113 + i] = [mcData.itemsByName.log2.id, i];
    exports[129 + i] = [mcData.itemsByName.log2.id, i];
}
for (let i = 0; i < 2; i++) exports[141 + i] = [mcData.itemsByName.sponge.id, i];
exports[143] = mcData.itemsByName.glass.id;
exports[144] = mcData.itemsByName.stained_glass.id;
exports[145] = mcData.itemsByName.lapis_block.id;
for (let i = 0; i < 3; i++) exports[146 + i] = [mcData.itemsByName.sandstone.id, i];
exports[149] = mcData.itemsByName.web.id;
exports[150] = mcData.itemsByName.grass.id;
exports[151] = [mcData.itemsByName.tallgrass.id, 2];
exports[154] = mcData.itemsByName.deadbush.id;
for (let i = 0; i < 16; i++) exports[157 + i] = [mcData.itemsByName.wool.id, i];
exports[196] = mcData.itemsByName.reeds.id;
for (let i = 0; i < 8; i++) exports[204 + i] = [mcData.itemsByName.wooden_slab.id, i % 6];
for (let i = 0; i < 3; i++) exports[212 + i] = [mcData.itemsByName.stone_slab.id, i];
exports[232] = mcData.itemsByName.brick_block.id;
exports[233] = mcData.itemsByName.bookshelf.id;
exports[234] = mcData.itemsByName.mossy_cobblestone.id;
exports[235] = mcData.itemsByName.obsidian.id;
exports[236] = mcData.itemsByName.torch.id;
exports[243] = mcData.itemsByName.mob_spawner.id;
exports[244] = mcData.itemsByName.oak_stairs.id;
exports[245] = mcData.itemsByName.chest.id;
exports[246] = mcData.itemsByName.crafting_table.id;
exports[248] = mcData.itemsByName.furnace.id;
exports[249] = mcData.itemsByName.ladder.id;
exports[250] = mcData.itemsByName.cobblestone.id;
exports[251] = mcData.itemsByName.snow.id;
exports[252] = mcData.itemsByName.ice.id;
exports[253] = mcData.itemsByName.snow.id;
exports[254] = mcData.itemsByName.cactus.id;
exports[256] = mcData.itemsByName.jukebox.id;
exports[265] = mcData.itemsByName.pumpkin.id;
exports[292] = mcData.itemsByName.brown_mushroom_block.id;
exports[293] = mcData.itemsByName.red_mushroom_block.id;
exports[297] = mcData.itemsByName.glass_pane.id;
exports[298] = mcData.itemsByName.melon.id;
exports[312] = mcData.itemsByName.end_stone.id;
exports[314] = mcData.itemsByName.dragon_egg.id;
exports[315] = mcData.itemsByName.sandstone_stairs.id;
exports[316] = mcData.itemsByName.ender_chest.id;
exports[317] = mcData.itemsByName.emerald_block.id;
exports[318] = mcData.itemsByName.spruce_stairs.id;
exports[319] = mcData.itemsByName.birch_stairs.id;
exports[320] = mcData.itemsByName.jungle_stairs.id;
exports[321] = mcData.itemsByName.birch_stairs.id;
exports[322] = mcData.itemsByName.birch_stairs.id;
exports[323] = mcData.itemsByName.command_block.id;
exports[324] = mcData.itemsByName.beacon.id;
for (let i = 0; i < 3; i++) exports[346 + i] = [mcData.itemsByName.anvil.id, i];
for (let i = 0; i < 16; i++) exports[354 + i] = [mcData.itemsByName.stained_hardened_clay.id, i];
exports[370] = mcData.itemsByName.barrier.id;
exports[372] = mcData.itemsByName.hay_block.id;
for (let i = 0; i < 16; i++) exports[373 + i] = [mcData.itemsByName.carpet.id, i];
exports[389] = mcData.itemsByName.stained_hardened_clay.id;
exports[390] = mcData.itemsByName.packed_ice.id;
for (let i = 0; i < 16; i++) exports[400 + i] = [mcData.itemsByName.stained_glass.id, i];
for (let i = 0; i < 32; i++) exports[468 + i] = [mcData.itemsByName.stained_hardened_clay.id, i % 16];
exports[547] = mcData.itemsByName.ice.id;
exports[585] = mcData.itemsByName.redstone.id;
exports[586] = mcData.itemsByName.redstone_torch.id;
exports[587] = mcData.itemsByName.redstone_block.id;
exports[588] = mcData.itemsByName.repeater.id;
exports[589] = mcData.itemsByName.comparator.id;
exports[590] = mcData.itemsByName.piston.id;
exports[591] = mcData.itemsByName.sticky_piston.id;
exports[592] = mcData.itemsByName.slime.id;
exports[595] = mcData.itemsByName.hopper.id;
exports[596] = mcData.itemsByName.dispenser.id;
exports[597] = mcData.itemsByName.dropper.id;
exports[600] = mcData.itemsByName.lever.id;
exports[604] = mcData.itemsByName.tripwire_hook.id;
exports[605] = mcData.itemsByName.trapped_chest.id;
exports[606] = mcData.itemsByName.tnt.id;
exports[608] = mcData.itemsByName.noteblock.id;
exports[609] = mcData.itemsByName.stone_button.id;
for (let i = 0; i < 8; i++) exports[611 + i] = mcData.itemsByName.wooden_button.id;
for (let i = 0; i < 8; i++) exports[623 + i] = mcData.itemsByName.wooden_pressure_plate.id;
exports[631] = mcData.itemsByName.iron_door.id;
exports[632] = mcData.itemsByName.wooden_door.id;
exports[633] = mcData.itemsByName.spruce_door.id;
exports[634] = mcData.itemsByName.birch_door.id;
exports[635] = mcData.itemsByName.jungle_door.id;
exports[636] = mcData.itemsByName.acacia_door.id;
exports[637] = mcData.itemsByName.dark_oak_door.id;
exports[638] = mcData.itemsByName.wooden_door.id;
exports[639] = mcData.itemsByName.wooden_door.id;
exports[640] = mcData.itemsByName.iron_trapdoor.id;
for (let i = 0; i < 8; i++) exports[641 + i] = mcData.itemsByName.trapdoor.id;
exports[680] = mcData.itemsByName.flint_and_steel.id;
exports[681] = mcData.itemsByName.apple.id;
exports[682] = mcData.itemsByName.bow.id;
exports[683] = mcData.itemsByName.arrow.id;
exports[684] = mcData.itemsByName.coal.id;
exports[685] = [mcData.itemsByName.coal.id, 1];
exports[686] = mcData.itemsByName.diamond.id;
exports[687] = mcData.itemsByName.emerald.id;
exports[688] = [mcData.itemsByName.dye.id, 4];
exports[692] = mcData.itemsByName.iron_ingot.id;
exports[696] = mcData.itemsByName.gold_ingot.id;
exports[699] = mcData.itemsByName.wooden_sword.id;
exports[700] = mcData.itemsByName.wooden_shovel.id;
exports[701] = mcData.itemsByName.wooden_pickaxe.id;
exports[702] = mcData.itemsByName.wooden_axe.id;
exports[703] = mcData.itemsByName.wooden_hoe.id;
exports[704] = mcData.itemsByName.stone_sword.id;
exports[705] = mcData.itemsByName.stone_shovel.id;
exports[706] = mcData.itemsByName.stone_pickaxe.id;
exports[707] = mcData.itemsByName.stone_axe.id;
exports[708] = mcData.itemsByName.stone_hoe.id;
exports[709] = mcData.itemsByName.golden_sword.id;
exports[710] = mcData.itemsByName.golden_shovel.id;
exports[711] = mcData.itemsByName.golden_pickaxe.id;
exports[712] = mcData.itemsByName.golden_axe.id;
exports[713] = mcData.itemsByName.golden_hoe.id;
exports[714] = mcData.itemsByName.iron_sword.id;
exports[715] = mcData.itemsByName.iron_shovel.id;
exports[716] = mcData.itemsByName.iron_pickaxe.id;
exports[717] = mcData.itemsByName.iron_axe.id;
exports[718] = mcData.itemsByName.iron_hoe.id;
exports[719] = mcData.itemsByName.diamond_sword.id;
exports[720] = mcData.itemsByName.diamond_shovel.id;
exports[721] = mcData.itemsByName.diamond_pickaxe.id;
exports[722] = mcData.itemsByName.diamond_axe.id;
exports[723] = mcData.itemsByName.diamond_hoe.id;
exports[724] = mcData.itemsByName.diamond_sword.id;
exports[725] = mcData.itemsByName.diamond_shovel.id;
exports[726] = mcData.itemsByName.diamond_pickaxe.id;
exports[727] = mcData.itemsByName.diamond_axe.id;
exports[728] = mcData.itemsByName.diamond_hoe.id;
exports[729] = mcData.itemsByName.stick.id;
exports[730] = mcData.itemsByName.bowl.id;
exports[731] = mcData.itemsByName.mushroom_stew.id;
exports[732] = mcData.itemsByName.string.id;
exports[733] = mcData.itemsByName.feather.id;
exports[734] = mcData.itemsByName.gunpowder.id;
exports[735] = mcData.itemsByName.wheat_seeds.id;
exports[736] = mcData.itemsByName.wheat.id;
exports[737] = mcData.itemsByName.bread.id;
exports[738] = mcData.itemsByName.leather_helmet.id;
exports[739] = mcData.itemsByName.leather_chestplate.id;
exports[740] = mcData.itemsByName.leather_leggings.id;
exports[741] = mcData.itemsByName.leather_boots.id;
exports[742] = mcData.itemsByName.chainmail_helmet.id;
exports[743] = mcData.itemsByName.chainmail_chestplate.id;
exports[744] = mcData.itemsByName.chainmail_leggings.id;
exports[745] = mcData.itemsByName.chainmail_boots.id;
exports[746] = mcData.itemsByName.iron_helmet.id;
exports[747] = mcData.itemsByName.iron_chestplate.id;
exports[748] = mcData.itemsByName.iron_leggings.id;
exports[749] = mcData.itemsByName.iron_boots.id;
exports[750] = mcData.itemsByName.diamond_helmet.id;
exports[751] = mcData.itemsByName.diamond_chestplate.id;
exports[752] = mcData.itemsByName.diamond_leggings.id;
exports[753] = mcData.itemsByName.diamond_boots.id;
exports[754] = mcData.itemsByName.golden_helmet.id;
exports[755] = mcData.itemsByName.golden_chestplate.id;
exports[756] = mcData.itemsByName.golden_leggings.id;
exports[757] = mcData.itemsByName.golden_boots.id;
exports[758] = mcData.itemsByName.diamond_helmet.id;
exports[759] = mcData.itemsByName.diamond_chestplate.id;
exports[760] = mcData.itemsByName.diamond_leggings.id;
exports[761] = mcData.itemsByName.diamond_boots.id;
exports[762] = mcData.itemsByName.flint.id;
exports[763] = mcData.itemsByName.porkchop.id;
exports[764] = mcData.itemsByName.cooked_porkchop.id;
exports[766] = mcData.itemsByName.golden_apple.id;
exports[767] = [mcData.itemsByName.golden_apple.id, 1];
for (let i = 0; i < 8; i++) exports[768 + i] = mcData.itemsByName.sign.id;
exports[776] = mcData.itemsByName.bucket.id;
exports[777] = mcData.itemsByName.water_bucket.id;
exports[778] = mcData.itemsByName.lava_bucket.id;
exports[779] = mcData.itemsByName.water_bucket.id;
exports[780] = mcData.itemsByName.snowball.id;
exports[781] = mcData.itemsByName.leather.id;
exports[782] = mcData.itemsByName.milk_bucket.id;
exports[791] = mcData.itemsByName.paper.id;
exports[792] = mcData.itemsByName.book.id;
exports[793] = mcData.itemsByName.slime_ball.id;
exports[794] = mcData.itemsByName.egg.id;
exports[795] = mcData.itemsByName.compass.id;
exports[797] = mcData.itemsByName.fishing_rod.id;
exports[798] = mcData.itemsByName.clock.id;
for (let i = 0; i < 4; i++) exports[801 + i] = [mcData.itemsByName.fish.id, i];
for (let i = 0; i < 2; i++) exports[805 + i] = [mcData.itemsByName.cooked_fish.id, i];
for (let i = 0; i < 2; i++) exports[807 + i] = mcData.itemsByName.dye.id;
exports[809] = [mcData.itemsByName.dye.id, 3];
for (let i = 0; i < 16; i++) exports[810 + i] = [mcData.itemsByName.dye.id, 15 - i];
exports[826] = [mcData.itemsByName.dye.id, 15];
exports[827] = mcData.itemsByName.bone.id;
exports[828] = mcData.itemsByName.sugar.id;
exports[829] = mcData.itemsByName.cake.id;
for (let i = 0; i < 16; i++) exports[830 + i] = mcData.itemsByName.bed.id;
exports[846] = mcData.itemsByName.cookie.id;
exports[847] = 358; // FILLED_MAP
exports[848] = mcData.itemsByName.shears.id;
exports[849] = mcData.itemsByName.melon.id;
exports[851] = mcData.itemsByName.pumpkin_seeds.id;
exports[852] = mcData.itemsByName.melon_seeds.id;
exports[853] = mcData.itemsByName.beef.id;
exports[854] = mcData.itemsByName.cooked_beef.id;
exports[855] = mcData.itemsByName.chicken.id;
exports[856] = mcData.itemsByName.cooked_chicken.id;
exports[857] = mcData.itemsByName.rotten_flesh.id;
exports[858] = mcData.itemsByName.ender_pearl.id;
exports[859] = mcData.itemsByName.blaze_rod.id;
exports[860] = mcData.itemsByName.ghast_tear.id;
exports[861] = mcData.itemsByName.gold_nugget.id;
exports[863] = mcData.itemsByName.potion.id;
exports[864] = mcData.itemsByName.glass_bottle.id;
exports[865] = mcData.itemsByName.spider_eye.id;
exports[866] = mcData.itemsByName.fermented_spider_eye.id;
exports[867] = mcData.itemsByName.blaze_powder.id;
exports[868] = mcData.itemsByName.magma_cream.id;
exports[869] = mcData.itemsByName.brewing_stand.id;
exports[870] = mcData.itemsByName.cauldron.id;
exports[871] = mcData.itemsByName.ender_eye.id;
exports[872] = mcData.itemsByName.speckled_melon.id;
exports[940] = mcData.itemsByName.experience_bottle.id;
exports[941] = mcData.itemsByName.fire_charge.id;
exports[942] = mcData.itemsByName.writable_book.id;
exports[943] = mcData.itemsByName.written_book.id;
for (let i = 0; i < 2; i++) exports[944 + i] = mcData.itemsByName.item_frame.id;
exports[946] = mcData.itemsByName.flower_pot.id;
exports[947] = mcData.itemsByName.carrot.id;
exports[948] = mcData.itemsByName.potato.id;
exports[949] = mcData.itemsByName.baked_potato.id;
exports[950] = mcData.itemsByName.poisonous_potato.id;
exports[951] = mcData.itemsByName.map.id;
exports[952] = mcData.itemsByName.golden_carrot.id;
exports[960] = mcData.itemsByName.pumpkin_pie.id;
exports[967] = mcData.itemsByName.rabbit.id;
exports[968] = mcData.itemsByName.cooked_rabbit.id;
exports[969] = mcData.itemsByName.rabbit_stew.id;
exports[973] = mcData.itemsByName.iron_horse_armor.id;
exports[974] = mcData.itemsByName.golden_horse_armor.id;
exports[975] = mcData.itemsByName.diamond_horse_armor.id;
exports[976] = mcData.itemsByName.iron_horse_armor.id;
exports[977] = mcData.itemsByName.lead.id;
exports[978] = mcData.itemsByName.name_tag.id;
exports[980] = mcData.itemsByName.mutton.id;
exports[981] = mcData.itemsByName.cooked_mutton.id;
exports[998] = [mcData.itemsByName.spawn_egg.id, 200];
exports[1005] = [mcData.itemsByName.potion.id, 1];
exports[1015] = mcData.itemsByName.record_13.id;
exports[1016] = mcData.itemsByName.record_cat.id;
exports[1017] = mcData.itemsByName.record_blocks.id;
exports[1018] = mcData.itemsByName.record_chirp.id;
exports[1019] = mcData.itemsByName.record_far.id;
exports[1020] = mcData.itemsByName.record_mall.id;
exports[1021] = mcData.itemsByName.record_mellohi.id;
exports[1022] = mcData.itemsByName.record_stal.id;
exports[1023] = mcData.itemsByName.record_strad.id;
exports[1024] = mcData.itemsByName.record_ward.id;
exports[1025] = mcData.itemsByName.record_11.id;
exports[1026] = mcData.itemsByName.record_wait.id;
exports[1027] = mcData.itemsByName.record_stal.id;
exports[1028] = mcData.itemsByName.record_stal.id;
exports[1033] = mcData.itemsByName.bow.id;
exports[1101] = mcData.itemsByName.diamond_sword.id;
exports[1102] = mcData.itemsByName.diamond_pickaxe.id;
exports[1103] = mcData.itemsByName.diamond_axe.id;
exports[1104] = mcData.itemsByName.diamond_shovel.id;
exports[1105] = mcData.itemsByName.diamond_hoe.id;
exports[1106] = mcData.itemsByName.diamond_helmet.id;
exports[1107] = mcData.itemsByName.diamond_chestplate.id;
exports[1108] = mcData.itemsByName.diamond_leggings.id;
exports[1109] = mcData.itemsByName.diamond_boots.id;
exports[1110] = mcData.itemsByName.ladder.id;
exports[1111] = mcData.itemsByName.apple.id;
exports[1112] = mcData.itemsByName.apple.id;
export default exports;